[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300