services:
  - type: web
    name: natural-nature-backend
    runtime: docker
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/app.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/java/openjdk
      - key: JAVA_VERSION
        value: 17

